### ISSUE TITLE
URH File for SD Card

### ISSUE THREAD

**Issue by ZS2AB** [DMFSouza/EvilCrowRF_HUN73R.0047#1]
Good day. 
Thank you for an interesting project and please excuse the simplicity of my question, I am a complete novice but am learning as I fumble my way through setting up of the Evil Crow.
Where do I find the "URH" file which needs to be copied to the SD card?
kind regards
Alistair

**Comment by DMFSouza** [comment]
Good morning, thank you very much for your feedback. Regarding your question, the URH is a folder that should be created on your SD card, where the files captured by your EvilCrowRF will be saved. When uploading the project, I indeed forgot to include this folder, but I am updating it right now. Once again, thank you for your feedback!

**Comment by ZS2AB** [comment]
Good morning

Thank you for your reply and assistance, it is much appreciated.

Kind regards
