### ISSUE TITLE
evil crow rf v2 not showing up on mobile phone

### ISSUE THREAD

**Issue by shanejohn15** [DMFSouza/EvilCrowRF_HUN73R.0047#2]
the website for this i think is sick with the analyzer and other capabilities but i cant get it to connect to my cell phones, it turns on once plugged in but wont show in wifi

**Comment by DMFSouza** [comment]
Perhaps it is set up as a hidden network. Please try going to the options to add a hidden network and enter the default SSID and password, then see if your issue is resolved.
